package org.datenlord
package ip.das

import spinal.core.{BlackBox, Bool, in, out}

/** black box of altera pll
 *
 * @param outClockCount clock signals generated by pll according to refclk
 */
case class AlteraPll(outClockCount: Int) extends BlackBox {
  val refclk = in Bool()
  val rst = in Bool()
  val outclks = out Vec(Bool(), outClockCount)
  outclks.zipWithIndex.map{ case (clk, i) => clk.setName(s"outclk_$i")}
}
