/*------------------------------------------------------------------------------
 * This code was generated by Spiral Multiplier Block Generator, www.spiral.net
 * Copyright (c) 2006, Carnegie Mellon University
 * All rights reserved.
 * The code is distributed under a BSD style license
 * (see http://www.opensource.org/licenses/bsd-license.php)
 *------------------------------------------------------------------------------ */

module multiplier_block (
    X,
    Y
);

  // Port mode declarations:
  input [23:0] X;
  output [47:0] Y;

  //Multipliers:

  wire [47:0]
    w1,
    w1024,
    w1023,
    w8388608,
    w8387585,
    w523776,
    w8911361,
    w262144,
    w9173505,
    w65536,
    w9239041;

  assign w1 = X;
  assign w1024 = w1 << 10;
  assign w1023 = w1024 - w1;
  assign w8388608 = w1 << 23;
  assign w8387585 = w8388608 - w1023;
  assign w523776 = w1023 << 9;
  assign w8911361 = w8387585 + w523776;
  assign w262144 = w1 << 18;
  assign w9173505 = w8911361 + w262144;
  assign w65536 = w1 << 16;
  assign w9239041 = w9173505 + w65536;

  assign Y = w9239041;

endmodule //multiplier_block
