package org.datenlord
package intel

import spinal.core.{BlackBox, Bool, in, out}

/** Altera Pll IP blackbox
 *
 * @param outClockCount clock signals generated by pll according to refclk
 */
case class AlteraPll(outClockCount: Int) extends BlackBox {
  val refclk = in Bool()
  val rst = in Bool()
  val outclks = out Vec(Bool(), outClockCount)
}